Fix GAE deployment version error in gcloud sdk v138.0.0.
In gcloud sdk v138.0.0,
gcloud app deploy with args `--version ""` will get error below:

ERROR: (gcloud.app.deploy) argument --version/-v: Bad value []: May only
contain lowercase letters, digits, and hyphens. Must begin and end with
a letter or digit. Must not exceed 63 characters.

So, if user didn't set the version and we want to use the gcloud
default generated version in this deployment, we just don't need to add
`--version`.