Use AWS SDK v2 call to create bucket
`#create` is not a valid call here in v2, resulting in:

    /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-resources-2.9.23/lib/aws-sdk-resources/collection.rb:80:in `method_missing': undefined method `create' for #<Aws::Resources::Collection:0x00000001357a90> (NoMethodError)
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.32/lib/dpl/provider/elastic_beanstalk.rb:106:in `create_bucket'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.32/lib/dpl/provider/elastic_beanstalk.rb:42:in `push_app'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.32/lib/dpl/provider.rb:146:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.32/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.32/lib/dpl/provider.rb:146:in `deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.32/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.32/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.32/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'

We use the v2 equivalent call to ensure that the bucket
exists.