Remove ~/.npmrc before running specs on gems
spec-npm writes to ~/.npmrc, which causes unslightly error
messages in subsequent specs

    Error: Failed to replace env in config: ${NPM_API_KEY}
        at /home/travis/.nvm/versions/node/v8.9.1/lib/node_modules/npm/lib/config/core.js:418:13
        at String.replace (<anonymous>)
        ⋮