Remove `docker_build` option for Google App Engine.
`docker_build` option has already been deprecated in gcloud
v112.0.0 and removed in gcloud v114.0.0

If we keep this option, we will get this error messsage:

```
ERROR: (gcloud.preview.app.deploy) Docker builds now use Container
Builder by default. To run a Docker build on
your own host, you can run:
    docker build -t gcr.io/<project>/<service.version> .
    gcloud docker push gcr.io/<project>/<service.version>
    gcloud preview app deploy --image-url=gcr.io/<project>/<service.version>
```